version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/spring-web-security-app-1.0-SNAPSHOT.war spring-web-security-app-1.0-SNAPSHOT.war
artifacts:
  files:
    - spring-web-security-app-1.0-SNAPSHOT.war
    - .ebextensions/**/*